steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: bash
  args:
  - -c
  - |
      gcloud functions deploy function_cicd \
      --gen2 \
      --runtime=python311 \
      --region=us-central1 \
      --source=. \
      --entry-point=function_cicd \
      --trigger-http \
      --allow-unauthenticated

options:
  logging: CLOUD_LOGGING_ONLY
